### ISSUE TITLE
Missing example-Files in the Documentation

### ISSUE THREAD

**Issue by minnten** [jjhelmus/nmrglue#136]
Hello,

when I try to download the Example-Data, for example this one https://nmrglue.readthedocs.io/en/latest/examples/plot_1d_freq.html , I get the error, that the data is not avialiable.

Greetings

**Comment by kaustubhmote** [comment]
Thanks for pointing this out. This is the correct link: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/nmrglue/example_plot_1d.zip

Since google code was shut down, all datasets in the examples are available at https://code.google.com/archive/p/nmrglue/downloads. It seems that there are still some places in the documentation where the links have not been corrected, this being one of them.
