### ISSUE TITLE
Request for New PyPI Release

### ISSUE THREAD

**Issue by fedejaure** [jjhelmus/nmrglue#220]
Are you considering publishing a new release on PyPI? There have been some updates since the last release, and it would be great to have them available.

**Comment by rserial** [comment]
Hi @jjhelmus, we want to publish a release of [spinsolveproc](https://github.com/rserial/spinsolveproc) on PyPI. The last nmrglue release works great, but we need the latest features in the repo for our library. Since PyPI doesn’t allow direct repo dependencies, could we get a new PyPI release of nmrglue? Thanks a lot!

**Comment by jjhelmus** [comment]
A new release would be great. I'll tag a commit and start the upload process.

**Comment by jjhelmus** [comment]
nmrglue version 0.11.0 is tagged and files are available on PyPI.

**Comment by fedejaure** [comment]
Thanks a lot, @jjhelmus! Really appreciate all the work!
